uclibc: Do not include __iconv_codesets into iconv utility
Backporting an upstream patch to fix a problem in the install step:

make[1]: Entering directory `/br/output/build/uclibc-0.9.33.2'
make[2]: Nothing to be done for `locale_headers'.
	CC utils/getconf
	STRIP -x -R .note -R .comment ../utils/getconf
	CC utils/iconv
../lib/libc.a(iconv.os):(.rodata+0x18): multiple definition of
`__iconv_codesets'
/tmp/ccVmV8Lq.o:(.rodata+0x18): first defined here
collect2: error: ld returned 1 exit status

Upstream commit:
	http://git.uclibc.org/uClibc/commit/?id=d46dc8bc88e38251bfa3712efe7abf62933f5419

Signed-off-by: Vicente Olivert Riera <Vincent.Riera@imgtec.com>

From d46dc8bc88e38251bfa3712efe7abf62933f5419 Mon Sep 17 00:00:00 2001
From: Peter S. Mazinger <ps.m@gmx.net>
Date: Thu, 24 Mar 2011 00:15:25 +0000
Subject: iconv: Do not include __iconv_codesets into iconv utility

Host iconv needs only L_iconv_main defined and __iconv_codesets
has to included, as host system does not provide it.
Keep __iconv_codesets out of iconv linked against uClibc.

Signed-off-by: Peter S. Mazinger <ps.m@gmx.net>
Signed-off-by: Bernhard Reutner-Fischer <rep.dot.nop@gmail.com>